#!/usr/bin/env python3
import socket
import ssl
import json
import argparse
import urllib.parse

def connectToServer(host, port):
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
        s = context.wrap_socket(s, server_hostname=host)
        s.connect((host, port))
        return s
    except Exception as e:
        print(f'Error connecting to server: {e}')
        return None

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('op', type=str, help='operation')
    parser.add_argument('arg1', type=str, help='file or url')
    parser.add_argument('arg2', type=str, help='file or url')

    args = parser.parse_args()

    op = args.op
    arg1 = args.arg1
    arg2 = args.arg2

    print(f'op: {op}, arg1: {arg1}, arg2: {arg2}')

if __name__ == "__main__":
    main()