#!/usr/bin/env python3
import socket
import ssl
import json
import argparse

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('op', type=str, help='operation')
    parser.add_argument('arg1', type=str, help='file or url')
    parser.add_argument('arg2', type=str, help='file or url')

    args = parser.parse_args()

    op = args.op
    arg1 = args.arg1
    arg2 = args.arg2

    print(f'op: {op}, arg1: {arg1}, arg2: {arg2}')

if __name__ == "__main__":
    main()